#%RAML 1.0
title: MuleSoft IDP Universal 🌐 Test Harness
version: v1
mediaType: application/json
protocols: HTTPS

baseUri: https://{host}/api/{version}
baseUriParameters:
  host:
    type: string
    example: mulesoft-idp-universal-test-harness-uupas5.m3jzw3-1.deu-c1.cloudhub.io

securedBy: mulesoft-basic-auth

/webapp:
  get:
    displayName: Webapp Home Page
    responses:
      "200":
        body:
          text/html:
            description: Index HTML Page
  /upload:
    post:
      displayName: Webapp File Upload
      body:
        multipart/form-data:
          fileTypes:
            - image/png
            - image/jpeg
            - application/pdf

  /actions/{actionId}/versions:
    uriParameters:
      actionId:
        type: field-actionId
    get:
      responses:
        "200":
          body:
            application/json:
              items:
                properties:
                  id:
                    example: 1.1.0
                    type: string
                  name:
                    example: 1.0.0 - PUBLISHED
                    type: string
    /{actionVersion}/executions/{executionId}:
      uriParameters:
        actionVersion:
          type: field-actionVersion
        executionId:
          type: field-executionId
      get:
        responses:
          "200":
            body:
              application/json:



securitySchemes:
  mulesoft-basic-auth:
    displayName: 🛡️ MuleSoft Basic Authentication
    type: Basic Authentication
    description: | 
      ### [Basic Authentication: Simple Policy](https://docs.mulesoft.com/gateway/latest/policies-included-basic-auth-simple) Enforces authentication according to the details configured in a security manager policy

types: # Considered use of Library, but the dependency was deemed to hinder adoption
  field-actionId:
    description: |-
      IDP Document Action Id 

      Published Document Action UUID
    example: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    type: string
    pattern: "[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?"
  field-actionVersion:
    displayName: IDP Document Action Id Version
    description: Document Action Version like 1.0.0
    default: 1.1.0
    example: 1.1.0
    type: string
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$
  field-executionId:
    displayName: IDP Execution Id
    description: IDP Execution Id returned after successful submission
    default: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
  field-ExecutionStatus:
    displayName: IDP Execution Status
    description: |
      ## [Execution Results Reference](https://docs.mulesoft.com/idp/automate-document-processing-with-the-idp-api#execution-status-reference).

      When you query the results of an execution, the IDP API returns the status which can be any of the following:

      - `ACKNOWLEDGED`: The document action execution request was received.
      - `IN_PROGRESS`: The execution started.
      - `RESULTS_PENDING`: The execution finished and IDP is processing the results.
      - `MANUAL_VALIDATION_REQUIRED`: The execution finished but the results need manual validation.
      - `FAILED`: The execution request finished unsuccessfully.
      - `PARTIAL_SUCCESS`: The execution request finished but some sub-tasks failed.
      - `SUCCEEDED`: The execution request finished successfully.
    default: IN_PROGRESS
    enum:
      - ACKNOWLEDGED
      - IN_PROGRESS
      - RESULTS_PENDING
      - MANUAL_VALIDATION_REQUIRED
      - FAILED
      - PARTIAL_SUCCESS
      - SUCCEEDED
    example: IN_PROGRESS
    type: string

  object-DocumentExecutionGetResponse:
    displayName: IDP Retrieve Execution Response Object
    type: object
    description:
    properties:
      pages?:
        type: array
        items: object-Page
      id?:
        type: field-executionId
      documentName?:
        type: string
      prompts?:
        type: object-Prompt
      status?:
        type: field-ExecutionStatus
  object-Page:
    displayName: IDP Retrieve Execution Response Page Object
    type: object
    properties:
      tables?:
        type: object
        properties: {}
      page?:
        type: string
      fields?:
        type: object
        properties: {}
      prompts?:
        type: object-Prompt
  object-Prompt:
    displayName: IDP Retrieve Execution Response Prompt Object
    type: object
    properties:
      answer?: object-Field
      source?:
        type: string
      prompt?:
        type: string
  object-Field:
    displayName: IDP Retrieve Execution Response Field Object
    type: object
    properties:
      value?:
        type: string
      geometry?:
        type: object
        properties:
          height:
            type: number
            required: false
          left:
            type: number
            required: false
          width:
            type: number
            required: false
          top:
            type: number
            required: false
      confidenceScore?:
        type: number

description: |

  protocols: HTTPS

  securedBy: 🛡️ MuleSoft Basic Authentication

  | Author | Date | Description
  | -------- | ------- | ------- |
  | G.Jeffcock | 23rd June 2024 | Launched| 
  |||| 
  ||||


documentation:
 - title: 📌 Why?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌


 - title: 📌 How?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌