#%RAML 1.0
title: MuleSoft IDP Universal 🌐 Test Harness
version: v1
mediaType: application/json
protocols: HTTPS

baseUri: https://{host}/api/{version}
baseUriParameters:
  host:
    type: string
    example: mulesoft-idp-universal-test-harness-uupas5.m3jzw3-1.deu-c1.cloudhub.io

securedBy: mulesoft-basic-auth

/webapp:
  get:
    displayName: Webapp Home Page
    responses:
      "200":
        body:
          text/html:
            description: Index HTML Page
  /upload:
    post:
      displayName: Webapp File Upload
      body:
        multipart/form-data:
          fileTypes:
            - image/png
            - image/jpeg
            - application/pdf

  /actions/{actionId}/versions:
    uriParameters:
      actionId:
        type: field-actionId
    get:
      responses:
        "200":
          body:
            application/json:
              items:
                properties:
                  id:
                    example: 1.1.0
                    type: string
                  name:
                    example: 1.0.0 - PUBLISHED
                    type: string
    /{actionVersion}/executions/{id}:
      uriParameters:
        actionVersion:
          type: field-actionId



securitySchemes:
  mulesoft-basic-auth:
    displayName: 🛡️ MuleSoft Basic Authentication
    type: Basic Authentication
    description: | 
      ### [Basic Authentication: Simple Policy](https://docs.mulesoft.com/gateway/latest/policies-included-basic-auth-simple) Enforces authentication according to the details configured in a security manager policy

types: # Considered use of Library, but the dependency was deemed to hinder adoption
  field-actionId:
    description: |-
      IDP Document Action Id 

      Published Document Action UUID
    example: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    type: string
    pattern: "[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?"
  field-actionVersion:
    displayName: IDP Document Action Id Version
    description: Document Action Version like 1.0.0
    default: 1.1.0
    example: 1.1.0
    type: string
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$
  field-executionId:
    displayName: IDP Execution Id
    description: IDP Execution Id returned after successful submission
    default: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$

description: |

  protocols: HTTPS

  securedBy: 🛡️ MuleSoft Basic Authentication

  | Author | Date | Description
  | -------- | ------- | ------- |
  | G.Jeffcock | 23rd June 2024 | Launched| 
  |||| 
  ||||


documentation:
 - title: 📌 Why?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌

 - title: 📌 How?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌